author: '@your_GitHub_username'
display:
  DISPLAY_SIZE: 80x160
  DISPLAY_ORIENTATION: landscape
  DISPLAY_RGB_LED: 85, 85, 85

static_images:
  background:
    PATH: background.png
    X: 0
    Y: 0
    WIDTH: 160
    HEIGHT: 80

static_text:
  hello:
    TEXT: Hello World !
    X: 0
    Y: 0
    FONT: fusion-pixel\fusion-pixel-12px-monospaced-zh_hans.otf
    FONT_SIZE: 12
    FONT_COLOR: 255, 255, 255
    BACKGROUND_IMAGE: background.png
    ALIGN: left # left / center / right
    ANCHOR: lt  # Check https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html
  hello_weact:
    TEXT: Hello WeAct Studio !
    X: 0
    Y: 16
    FONT: fusion-pixel\fusion-pixel-12px-monospaced-zh_hans.otf
    FONT_SIZE: 12
    FONT_COLOR: 255, 255, 255
    BACKGROUND_IMAGE: background.png
    ALIGN: left # left / center / right
    ANCHOR: lt  # Check https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html